version: "3.3"
services:
  Bob:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      app_net:
        ipv4_address: 172.16.238.3
  
  Alice:
    depends_on:
      - Bob
    networks:
      app_net:
        ipv4_address: 172.16.238.6
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      SERVERADDR: "Bob:5001" 

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
  data: