# syntax=docker/dockerfile:1

FROM golang:1.19.2-alpine

ENV SERVERADDR="127.0.0.1"

WORKDIR /app

COPY ./src/go.mod ./
COPY ./src/go.sum ./

RUN go mod download

COPY ./src ./

RUN go build -o /client ./cmd/client/main.go

CMD ["sh", "-c", "/client --serverAddr ${SERVERADDR} --random"]