version: "3.3"
services:
  bob:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      app_net:
        ipv4_address: 192.168.0.3
  
  alice:
    depends_on:
      - Bob
    networks:
      app_net:
        ipv4_address: 192.168.0.6
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      SERVERADDR: "Bob:5001" 

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"

volumes:
  data: