# syntax=docker/dockerfile:1

FROM golang:1.19.2-alpine

WORKDIR /app

COPY ./src/go.mod ./
COPY ./src/go.sum ./

RUN go mod download

COPY ./src ./

RUN go build -o /server ./cmd/server/main.go

EXPOSE 5001

CMD ["sh", "-c", "/server"]